### ISSUE TITLE
Documentar los requerimientos

### ISSUE THREAD

**Issue by alexangupe** [Apollo-XVIII/semana-1-2#8]
Documentar los requerimientos del proyecto en el formato indicado

**Comment by etauchipi** [comment]
[Tablas.xlsx](https://github.com/Apollo-XVIII/semana-1-2/files/7131425/Tablas.xlsx)

Definición de la estructura de datos necesarios para el proyecto Simply Coffee, Grupo Apollo XVIII - MisiónTic 2022 - Grupo 61

**Comment by etauchipi** [comment]
Se realiza ajuste a la tabla de recetas.

Se adiciona campo Receta y se adiciona campo ingredientes, para separar los dos aspectos de la preparación. Se actualiza en el Repositorio

**Comment by etauchipi** [comment]
En la reunión de hoy se definió una ajuste para la tabla de recetas. 

Se adiciona Ingredientes y Receta, para separar los dos conceptos y poder mostrar la info de una manera estructurada.

Se actualiza plantilla del archivo Excel y se adiciona un comment

**Comment by etauchipi** [comment]
Se crea un branch adicional (dev) donse se alojará el diseño final del proyecto, dejando a desarrollo como repositorio para realizar y dejar todas las pruebas de los trabajos de cada integrante.

Se organiza el nuevo branch con la estructura definitiva
